In [2]:
import numpy as np
arr_1D=np.array([1,2,3,4,5,6])
print("1D array:")
print(arr_1D)

1D array:
[1 2 3 4 5 6]


In [5]:
arr_2D=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2D array:")
print(arr_2D)

2D array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
arr_3D=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("3D array:")
print(arr_3D)

3D array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [7]:
arr_1D=np.array([1,2,3,4,5,6])
arr_2D=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_3D=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(arr_1D.data)

print("shape of 1D array:",arr_1D.shape)
print("shape of 2D array:",arr_2D.shape)
print("shape of 3D array:",arr_3D.shape)

print("Data Type of 1D array:",arr_1D.dtype)

reshaped_1D=arr_1D.reshape(2,3)
print("Reshaped array is:",reshaped_1D)

shape of 1D array: (6,)
shape of 2D array: (2, 5)
shape of 3D array: (1, 3, 3)
Data Type of 1D array: int32
Reshaped array is: [[1 2 3]
 [4 5 6]]


In [4]:
zeros_arr=np.zeros((4,5))
print("Zeros array:\n", zeros_arr)
ones_arr=np.ones((3,4))
print("Ones array:\n",ones_arr)
full_arr=np.full((2,2),7)
identity_arr=np.eye(4)
print("Identity matrix:\n", identity_arr)


Zeros array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
range_arr=np.arange(1,20,2)
print("Range from 1 to 20(Odd NO)",range_arr)
lin_arr=np.linspace(0,5,5)
print("linspace array:", lin_arr)
rand_arr = np.random.rand(2, 3)      
randint_arr = np.random.randint(1, 100, size=(2, 3))  
print("Random float array:\n", rand_arr)
print("Random integer array:\n", randint_arr)


Range from 1 to 20(Odd NO) [ 1  3  5  7  9 11 13 15 17 19]
linspace array: [0.   1.25 2.5  3.75 5.  ]
Random float array:
 [[0.28538324 0.26485737 0.79778852]
 [0.9334251  0.07376261 0.58973955]]
Random integer array:
 [[60 42 83]
 [ 1  9 69]]


In [21]:
excercise_1=np.zeros((2,3))
excercise_2=np.arange(10,20,3)
print("Zeros array\n",excercise_1)
print("Range from 10 to 20\n ",excercise_2)

Zeros array
 [[0. 0. 0.]
 [0. 0. 0.]]
Range from 10 to 20
  [10 13 16 19]


In [26]:
sample=np.array([[1,2,3],[4,5,6]])
print("Array is:\n",sample)
print("Shape of array:",sample.shape)
print("Dimention of array:",sample.ndim)
print("Data type of array:",sample.dtype)
print("Size of array:",sample.size)


Array is:
 [[1 2 3]
 [4 5 6]]
Shape of array: (2, 3)
Dimention of array: 2
Data type of array: int32
Size of array: 6


In [27]:
reshaped=sample.reshape(3,2)
print("Reshaped array is:\n",reshaped)
flat=sample.flatten()
print("Flattened:", flat)
print("Transpose of array is\n",sample.T)

Reshaped array is:
 [[1 2]
 [3 4]
 [5 6]]
Flattened: [1 2 3 4 5 6]
Transpose of array is
 [[1 4]
 [2 5]
 [3 6]]


In [29]:
a=np.array([1,2,3])
b=np.array([4,5,6])
joined=np.concatenate((a,b))
print("Concatenated:", joined)
stacked_v=np.vstack((a,b))
stacked_h=np.hstack((a,b))
print("Vertical stack:\n", stacked_v)
print("Horizontal stack:", stacked_h)

Concatenated: [1 2 3 4 5 6]
Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack: [1 2 3 4 5 6]


In [3]:
unsorted=np.array([5,6,2,3,1,4])
sorted=np.sort(unsorted)
print("Original:",unsorted)
print("Sorted array:",sorted)

Original: [5 6 2 3 1 4]
Sorted array: [1 2 3 4 5 6]


In [4]:
example= np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", example.shape)
print("Size:", example.size)
print("Reshaped:\n", example.reshape(3, 2))

Shape: (2, 3)
Size: 6
Reshaped:
 [[1 2]
 [3 4]
 [5 6]]


In [5]:
x=np.array([10,20,30,40,50])
y=np.array([1,2,3,4,5])
print("Addition:",x+y)
print("Subtraction:",x-y)
print("Multiplication:",x*y)
print("Division:",x/y)
print("Power:",x**2)
print("Power:",y**3)

Addition: [11 22 33 44 55]
Subtraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [10. 10. 10. 10. 10.]
Power: [ 100  400  900 1600 2500]
Power: [  1   8  27  64 125]


In [7]:
data=np.array([10,40,50,78,90])
print("Sum:",np.sum(data))
print("Mean:",np.mean(data))
print("Maximum:",np.max(data))
print("Minimum:",np.min(data))
print("Standard Deviaton:",np.std(data))
print("Variance:",np.var(data))


Sum: 268
Mean: 53.6
Maximum: 90
Minimum: 10
Standard Deviaton: 28.35207223467096
Variance: 803.8399999999999


In [9]:
numbers=np.array([10,50,60,87,45])
print("Square root:\n",np.sqrt(numbers))
print("Exponential:\n",np.exp(numbers))
print("Natural Log:\n",np.log(numbers))
print("Sine:\n",np.sin(numbers))


Square root:
 [3.16227766 7.07106781 7.74596669 9.32737905 6.70820393]
Exponential:
 [2.20264658e+04 5.18470553e+21 1.14200739e+26 6.07603023e+37
 3.49342711e+19]
Natural Log:
 [2.30258509 3.91202301 4.09434456 4.46590812 3.80666249]
Sine:
 [-0.54402111 -0.26237485 -0.30481062 -0.82181784  0.85090352]


In [10]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

print("Element-wise multiplication:\n", m1 * m2)
print("Matrix multiplication (dot):\n", np.dot(m1, m2))
print("Matrix multiplication (matmul):\n", np.matmul(m1, m2))

Element-wise multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication (dot):
 [[19 22]
 [43 50]]
Matrix multiplication (matmul):
 [[19 22]
 [43 50]]


In [11]:
p = np.array([2, 4, 6, 8, 10])
q = np.array([1, 3, 5, 7, 9])

example_sum = p + q
example_product = p * q
print("Sum:", example_sum)
print("Product:", example_product)
print("Mean of sum:", np.mean(example_sum))

Sum: [ 3  7 11 15 19]
Product: [ 2 12 30 56 90]
Mean of sum: 11.0


In [13]:
arr=np.array([10,30,50,60,90])
print("Full array:\n",arr)
print("First element:",arr[0])
print("Last array:",arr[-1])
print("Elements from index 1 to 3:", arr[1:4])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])


Full array:
 [10 30 50 60 90]
First element: 10
Last array: 90
Elements from index 1 to 3: [30 50 60]
Every second element: [10 50 90]
Reversed array: [90 60 50 30 10]


In [14]:
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("Matrix:\n", matrix)
print("Element at row 1, col 2:", matrix[1, 2])
print("First row:", matrix[0, :])
print("First column:", matrix[:, 0])
print("Sub-matrix (rows 0-1, cols 1-2):\n", matrix[0:2, 1:3])

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at row 1, col 2: 6
First row: [1 2 3]
First column: [1 4 7]
Sub-matrix (rows 0-1, cols 1-2):
 [[2 3]
 [5 6]]
