In [2]:
import numpy as np
arr_1D=np.array([1,2,3,4,5,6])
print("1D array:")
print(arr_1D)

1D array:
[1 2 3 4 5 6]


In [5]:
arr_2D=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2D array:")
print(arr_2D)

2D array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
arr_3D=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("3D array:")
print(arr_3D)

3D array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [7]:
arr_1D=np.array([1,2,3,4,5,6])
arr_2D=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr_3D=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(arr_1D.data)

print("shape of 1D array:",arr_1D.shape)
print("shape of 2D array:",arr_2D.shape)
print("shape of 3D array:",arr_3D.shape)

print("Data Type of 1D array:",arr_1D.dtype)

reshaped_1D=arr_1D.reshape(2,3)
print("Reshaped array is:",reshaped_1D)

shape of 1D array: (6,)
shape of 2D array: (2, 5)
shape of 3D array: (1, 3, 3)
Data Type of 1D array: int32
Reshaped array is: [[1 2 3]
 [4 5 6]]


In [4]:
zeros_arr=np.zeros((4,5))
print("Zeros array:\n", zeros_arr)
ones_arr=np.ones((3,4))
print("Ones array:\n",ones_arr)
full_arr=np.full((2,2),7)
identity_arr=np.eye(4)
print("Identity matrix:\n", identity_arr)


Zeros array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
range_arr=np.arange(1,20,2)
print("Range from 1 to 20(Odd NO)",range_arr)
lin_arr=np.linspace(0,5,5)
print("linspace array:", lin_arr)
rand_arr = np.random.rand(2, 3)      
randint_arr = np.random.randint(1, 100, size=(2, 3))  
print("Random float array:\n", rand_arr)
print("Random integer array:\n", randint_arr)


Range from 1 to 20(Odd NO) [ 1  3  5  7  9 11 13 15 17 19]
linspace array: [0.   1.25 2.5  3.75 5.  ]
Random float array:
 [[0.28538324 0.26485737 0.79778852]
 [0.9334251  0.07376261 0.58973955]]
Random integer array:
 [[60 42 83]
 [ 1  9 69]]


In [21]:
excercise_1=np.zeros((2,3))
excercise_2=np.arange(10,20,3)
print("Zeros array\n",excercise_1)
print("Range from 10 to 20\n ",excercise_2)

Zeros array
 [[0. 0. 0.]
 [0. 0. 0.]]
Range from 10 to 20
  [10 13 16 19]


In [26]:
sample=np.array([[1,2,3],[4,5,6]])
print("Array is:\n",sample)
print("Shape of array:",sample.shape)
print("Dimention of array:",sample.ndim)
print("Data type of array:",sample.dtype)
print("Size of array:",sample.size)


Array is:
 [[1 2 3]
 [4 5 6]]
Shape of array: (2, 3)
Dimention of array: 2
Data type of array: int32
Size of array: 6


In [27]:
reshaped=sample.reshape(3,2)
print("Reshaped array is:\n",reshaped)
flat=sample.flatten()
print("Flattened:", flat)
print("Transpose of array is\n",sample.T)

Reshaped array is:
 [[1 2]
 [3 4]
 [5 6]]
Flattened: [1 2 3 4 5 6]
Transpose of array is
 [[1 4]
 [2 5]
 [3 6]]


In [29]:
a=np.array([1,2,3])
b=np.array([4,5,6])
joined=np.concatenate((a,b))
print("Concatenated:", joined)
stacked_v=np.vstack((a,b))
stacked_h=np.hstack((a,b))
print("Vertical stack:\n", stacked_v)
print("Horizontal stack:", stacked_h)

Concatenated: [1 2 3 4 5 6]
Vertical stack:
 [[1 2 3]
 [4 5 6]]
Horizontal stack: [1 2 3 4 5 6]
